export const dataPrimitive = [
  {
    key: 1,
    name: "Nguyễn Văn A",
    dob: "1940/01/30",
    gen: "Nam",
    phone: "0969290646",
    tags: "Ông tổ",
    job: "Giáo viên",
    nof: "",
    nom: "",
    how: "Nguyễn Thị B",
    degree: "Tốt nghiệp đại học",
    status: "Bình thường",
  },
  {
    key: 2,
    name: "Nguyễn Thị C",
    dob: "1965/01/30",
    gen: "Nam",
    phone: "0969290646",
    tags: "Trưởng họ",
    job: "Bác Sĩ",
    nof: "",
    nom: "",
    how: "Nguyễn Văn A",
    degree: "Tốt nghiệp đại học",
    status: "Bình thường",
  },
  {
    key: 3,
    name: "Nguyễn Văn E",
    dob: "1967/01/30",
    gen: "Nam",
    phone: "0969290646",
    tags: "Phó họ",
    job: "Giáo viên",
    nof: "Nguyễn Văn A",
    nom: "Nguyễn Thị C",
    how: "Văn A",
    degree: "Tốt nghiệp đại học",
    status: "Bình thường",
  },
  {
    key: 4,
    name: "Nguyễn Thị F",
    dob: "1969/01/30",
    gen: "Nữ",
    phone: "0969290646",
    tags: "Thành viên",
    job: "Giáo viên",
    nof: "",
    nom: "",
    how: "Nguyễn Văn E",
    degree: "Tốt nghiệp đại học",
    status: "Bình thường",
  },
];
