export const dataPrimitive = [
  {
    id: 1,
    name: "Nguyễn Văn A",
    pids: [2],
    mid: null,
    fid: null,
    dob: "1940/01/30",
    gender: "male",
    phone: "0969290646",
    tags: "Ông tổ",
    job: "Giáo viên",
    degree: "Tốt nghiệp đại học",
    status: "Bình thường",
    img: "https://cdn.balkan.app/shared/f1.png",
  },
  {
    id: 2,
    name: "Queen Elizabeth",
    pids: [1],
    mid: null,
    fid: null,
    dob: "1965/01/30",
    gender: "female",
    phone: "0969290646",
    tags: "Trưởng họ",
    job: "Bác Sĩ",
    degree: "Tốt nghiệp đại học",
    status: "Bình thường",
    img: "https://cdn.balkan.app/shared/f2.png",

  },
  {
    id: 3,
    name: "Queen Elizabeth II",
    pids: [4],
    mid: 2,
    fid: 1,
    dob: "1967/01/30",
    gender: "female",
    phone: "0969290646",
    tags: "Phó họ",
    job: "Giáo viên",
    degree: "Tốt nghiệp đại học",
    status: "Bình thường",
    img: "https://cdn.balkan.app/shared/f5.png",

  },
  {
    id: 4,
    name: "Prince Philip",
    pids: [3],
    mid: null,
    fid: null,
    dob: "1969/01/30",
    gender: "female",
    phone: "0969290646",
    tags: "Thành viên",
    job: "Giáo viên",
    degree: "Tốt nghiệp đại học",
    status: "Bình thường",
    img: "https://cdn.balkan.app/shared/f3.png",

  }, 
  {
    id: 5,
    name: "Princess Margaret",
    pids: null,
    mid: 2,
    fid: 1,
    dob: "1969/01/30",
    gender: "male",
    phone: "0969290646",
    tags: "Thành viên",
    job: "Giáo viên",
    degree: "Tốt nghiệp đại học",
    status: "Bình thường",
    img: "https://cdn.balkan.app/shared/f6.png",
  },
  {
    id: 6,
    name: "Charles",
    pids: [7],
    mid: 3,
    fid: 4,
    dob: "1969/01/30",
    gender: "male",
    phone: "0969290646",
    tags: "Thành viên",
    job: "Giáo viên",
    degree: "Tốt nghiệp đại học",
    status: "Bình thường",
    img: "https://cdn.balkan.app/shared/f8.png",
  },
];
