export const dataPrimitive = [
  {
    id: 1,
    name: "Nguyễn Văn A",
    pids: [2],
    mid: null,
    fid: null,
    dob: "1940/01/30",
    gender: "male",
    phone: "0969290646",
    tags: "Ông tổ",
    job: "Giáo viên",
    degree: "Tốt nghiệp đại học",
    status: "Bình thường",
    img: "https://cdn.balkan.app/shared/f1.png",
  },
  {
    id: 2,
    name: "Nguyễn Thị C",
    pids: [1],
    mid: null,
    fid: null,
    dob: "1965/01/30",
    gender: "male",
    phone: "0969290646",
    tags: "Trưởng họ",
    job: "Bác Sĩ",
    degree: "Tốt nghiệp đại học",
    status: "Bình thường",
    img: "https://cdn.balkan.app/shared/f2.png",

  },
  {
    id: 3,
    name: "Nguyễn Văn E",
    pids: [4],
    mid: 2,
    fid: 1,
    dob: "1967/01/30",
    gender: "male",
    phone: "0969290646",
    tags: "Phó họ",
    job: "Giáo viên",
    degree: "Tốt nghiệp đại học",
    status: "Bình thường",
    img: "https://cdn.balkan.app/shared/f5.png",

  },
  {
    id: 4,
    name: "Nguyễn Thị F",
    pids: [3],
    mid: null,
    fid: null,
    dob: "1969/01/30",
    gender: "female",
    phone: "0969290646",
    tags: "Thành viên",
    job: "Giáo viên",
    degree: "Tốt nghiệp đại học",
    status: "Bình thường",
    img: "https://cdn.balkan.app/shared/f3.png",

  }, 
];
